//Q1
SELECT
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '999,999')|| '€' AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY 
    T.TRIMESTRE ,P.CATEGORIE
ORDER BY 
    P.CATEGORIE, TRIMESTRE,
    TO_CHAR(SUM(V.MONTANT), '999,999') DESC;

//Q2
SELECT 
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(T.TRIMESTRE ,P.CATEGORIE)
ORDER BY 
    P.CATEGORIE,TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;
    
//Q3
SELECT 
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(T.TRIMESTRE), ROLLUP(P.CATEGORIE)
ORDER BY 
    P.CATEGORIE,T.TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;
    
//Q4
SELECT 
    DECODE(GROUPING(P.CATEGORIE), 1, 'TOTAL', P.CATEGORIE) AS CATEGORIE,
    DECODE(GROUPING(T.TRIMESTRE), 1, 'TOTAL', T.TRIMESTRE) AS TRIMESTRE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(T.TRIMESTRE), ROLLUP(P.CATEGORIE)
ORDER BY 
    GROUPING(P.CATEGORIE), 
    GROUPING(T.TRIMESTRE), 
    P.CATEGORIE,
    T.TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;

//Q5
SELECT 
    ROW_NUMBER() OVER (PARTITION BY GROUPING(P.CATEGORIE) ORDER BY SUM(V.MONTANT) DESC) AS RANG,
    DECODE(GROUPING(P.CATEGORIE), 1, 'TOTAL', P.CATEGORIE) AS CATEGORIE,
    DECODE(GROUPING(T.TRIMESTRE), 1, 'TOTAL', T.TRIMESTRE) AS TRIMESTRE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(T.TRIMESTRE), ROLLUP(P.CATEGORIE)
ORDER BY 
    GROUPING(P.CATEGORIE), 
    GROUPING(T.TRIMESTRE), 
    P.CATEGORIE,
    T.TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;
    
//Q6
SELECT 
    RANK() OVER (PARTITION BY TRIMESTRE ORDER BY SUM(V.MONTANT) DESC) AS RANG,
    DECODE(GROUPING(P.CATEGORIE), 1, 'TOTAL', P.CATEGORIE) AS CATEGORIE,
    DECODE(GROUPING(T.TRIMESTRE), 1, 'TOTAL', T.TRIMESTRE) AS TRIMESTRE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE,
    TO_CHAR(SUM(V.MONTANT) * 100.0 / SUM(SUM(V.MONTANT)) OVER (PARTITION BY T.TRIMESTRE), '999.99') || '%' AS POURCENTAGE_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(T.TRIMESTRE), ROLLUP(P.CATEGORIE)
ORDER BY 
    GROUPING(P.CATEGORIE), 
    GROUPING(T.TRIMESTRE), 
    RANG,
    P.CATEGORIE,
    T.TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;
    
//Q7
SELECT 
    L.ZONEGEOGRAPHIQUE AS ZONE,
    L.PAYS AS PAYS,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_PAYS,
    TO_CHAR(SUM(V.MONTANT) * 100.0 / SUM(SUM(V.MONTANT)) OVER (PARTITION BY L.ZONEGEOGRAPHIQUE), '999.99') || '%' AS POURCENTAGE_VENTES_ZONE
FROM 
    VENTE V,
    LOCALISATION L
WHERE  L.LID = V.LID 
GROUP BY ROLLUP(L.ZONEGEOGRAPHIQUE, L.PAYS)
ORDER BY 
    L.ZONEGEOGRAPHIQUE,
    POURCENTAGE_VENTES_ZONE DESC;


//Q8

SELECT
    RANG,
    PAYS,
    MONTANT_VENTES_PAYS
FROM (
    SELECT
        ROW_NUMBER() OVER (ORDER BY SUM(V.MONTANT) DESC) AS RANG,
        L.PAYS AS PAYS,
        TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_PAYS
    FROM 
        VENTE V
    JOIN 
        LOCALISATION L ON L.LID = V.LID 
    GROUP BY 
        L.PAYS
)
WHERE
    RANG <= 3
ORDER BY 
    RANG;
    
//Q9

SELECT
    ZONE,
    PAYS,
    MONTANT_VENTES_PAYS,
    POURCENTAGE_VENTES_ZONE
FROM (
    SELECT
        L.ZONEGEOGRAPHIQUE AS ZONE,
        L.PAYS AS PAYS,
        TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_PAYS,
        RANK() OVER (PARTITION BY L.ZONEGEOGRAPHIQUE ORDER BY SUM(V.MONTANT) DESC) AS RANG,
        TO_CHAR(SUM(V.MONTANT) * 100.0 / SUM(SUM(V.MONTANT)) OVER (PARTITION BY L.ZONEGEOGRAPHIQUE), '999.99') || '%' AS POURCENTAGE_VENTES_ZONE
    FROM 
        VENTE V
    JOIN 
        LOCALISATION L ON L.LID = V.LID 
    GROUP BY ROLLUP(L.ZONEGEOGRAPHIQUE, L.PAYS)
)
WHERE
    RANG <= 3
ORDER BY 
    ZONE,
    POURCENTAGE_VENTES_ZONE DESC;