//Q1
SELECT 
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '999,999')|| '€' AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY 
    T.TRIMESTRE ,P.CATEGORIE
ORDER BY 
    P.CATEGORIE, TRIMESTRE,
    TO_CHAR(SUM(V.MONTANT), '999,999') DESC;
        
//Q2

SELECT 
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(T.TRIMESTRE ,P.CATEGORIE)
ORDER BY 
    P.CATEGORIE,TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;

//Q3

SELECT 
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(P.CATEGORIE,T.TRIMESTRE), ROLLUP(T.TRIMESTRE,P.CATEGORIE)
ORDER BY 
    P.CATEGORIE,T.TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;

//Q4
SELECT 
    T.TRIMESTRE AS TRIMESTRE,
    P.CATEGORIE,
    TO_CHAR(SUM(V.MONTANT), '9999999') AS MONTANT_VENTES_TRIMESTRE
FROM 
    TEMPS T, 
    VENTE V, 
    PRODUIT P 
WHERE 
    T.TID = V.TID 
    AND P.PID = V.PID 
GROUP BY ROLLUP(P.CATEGORIE,T.TRIMESTRE), ROLLUP(T.TRIMESTRE,P.CATEGORIE)
ORDER BY 
    P.CATEGORIE,T.TRIMESTRE,
    MONTANT_VENTES_TRIMESTRE DESC;
    
    
-- Q5
